---
- name: Instalar o nginx
  ansible.builtin.apt:
    name: "nginx={{ nginx_version }}"
    update_cache: yes
    state: present

- name: Configurando o nginx
  ansible.builtin.copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: 0644

- name: Renderizar os arquivos de configuração extras
  ansible.builtin.template:
    src: include.conf.j2
    dest: "/etc/nginx/conf.d/{{ item.filename }}.conf"
    owner: root
    group: root
    mode: 0644
  loop: "{{ nginx_extra_conf }}"

- name: Habilitando nginx
  ansible.builtin.service:
    enabled: yes
    name: nginx
    state: started
