name: "Valida role ansible"
  
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  validando_ansible:
    uses: "rafaelm93/cicd_centralizado/.github/workflows/ansible_valida_role.yaml@feat/action-valida-ansible"
    secrets:
      token: ${{ secrets.TOKEN }}